name: test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: mattdv57/mattdv-testrepo:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull mattdv57/mattdv-testrepo:latest
      - name: Delete Old docker container
        run: sudo docker rm -f mattdv-testrepo-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name mattdv-testrepo-container mattdv57/mattdv-testrepo
